name: Build Search Index And Meta Data

on:
  workflow_call:
    inputs:
      site_root:
        required: true
        type: string
      exclude_paths:
        required: false
        type: string
      meta_data_output:
        required: true
        type: string
      index_output:
        required: true
        type: string
      key_tags:
        required: false
        type: string


jobs:
  build_search_index_and_meta_data:
    name: Build Search Index And Meta Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - run: |
        pip3 install -r ./requirements.txt
        python3 generate_search_index.py {{ inputs.site_root }} {{ inputs.exclude_paths }} {{ inputs.key_tags }}
        python3 generate_search_metadata.py {{ inputs.site_root }} {{ inputs.exclude_paths }} {{ inputs.meta_data_output }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - run: echo "$(cat ./search_json.json)" | node build_ticket_index.js {{ inputs.fields }} > {{ inputs.index_output }}